package musicstoremanagement;

import java.awt.Color;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

public class AddAlbums extends javax.swing.JFrame {

    private TrackInfo trackinfo;
    private Album album;
    private Controller controller;

    /**
     * Creates new form AddAlbums
     */
    public AddAlbums() {
        initComponents();
        setGenres();
        SpinnerModel model = new SpinnerNumberModel(5, 1, 5, 1);
        albumRatingTxt.setModel(model);
       

        model = new SpinnerDateModel();
        rYearTxt.setModel(model);

        JSpinner.DateEditor editor = new JSpinner.DateEditor(rYearTxt, "yyyy");
        rYearTxt.setEditor(editor);

        model = new SpinnerNumberModel(1, 1, 200, 1);
        quantityTxt.setModel(model);

        changeSpinnerBg(albumRatingTxt);
        changeSpinnerBg(rYearTxt);
        changeSpinnerBg(quantityTxt);
        controller = new Controller();
        id_txt.setText(String.valueOf(controller.getLastRecord() + 1));
    }

    private void changeSpinnerBg(JSpinner spinner) {
        JTextField tf = ((JSpinner.DefaultEditor) spinner.getEditor()).getTextField();
        tf.setBackground(new Color(221, 221, 221));
        tf.setHorizontalAlignment(JTextField.CENTER);
        genreTxt.setBackground(new Color(221, 221, 221));

    }

    private String getReleaseYear() {
        Object value = rYearTxt.getValue();
        if (value instanceof Date) {
            Date date = (Date) value;
            SimpleDateFormat format = new SimpleDateFormat("yyy");
            String year = format.format(date);
            return year;
        }
        return "0000";
    }

    private void setGenres() {
        trackinfo = new TrackInfo();
        album = new Album();
        genreTxt.removeAllItems();
        for (String genre : album.getGenres()) {
            genreTxt.addItem(genre);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        id_txt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        title_txt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        genreTxt = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        albumRatingTxt = new javax.swing.JSpinner();
        rYearTxt = new javax.swing.JSpinner();
        quantityTxt = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("New Albums");
        setBackground(new java.awt.Color(210, 210, 210));
        setBounds(new java.awt.Rectangle(40, 40, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Add Albums");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 200, 60));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 77, 122, 38));

        id_txt.setEditable(false);
        id_txt.setBackground(new java.awt.Color(221, 221, 221));
        id_txt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        id_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(id_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 77, 140, 38));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 121, 124, 38));

        title_txt.setBackground(new java.awt.Color(221, 221, 221));
        title_txt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        title_txt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        title_txt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });
        getContentPane().add(title_txt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 121, 140, 38));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Rating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 165, 124, 38));

        jLabel5.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel5.setText("Release Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 206, 124, 38));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 247, 124, 38));

        jButton3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/save.png"))); // NOI18N
        jButton3.setText("Save Album");
        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusPainted(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 380, 150, 40));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Genre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 285, 124, 38));

        genreTxt.setBackground(new java.awt.Color(221, 221, 221));
        genreTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        genreTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        genreTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        genreTxt.setFocusable(false);
        genreTxt.setLightWeightPopupEnabled(false);
        genreTxt.setRequestFocusEnabled(false);
        genreTxt.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(genreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 285, 140, 38));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/add.png"))); // NOI18N
        jButton1.setText("Add Tracks");
        jButton1.setBorder(null);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(14, 379, -1, 43));

        albumRatingTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        albumRatingTxt.setModel(new javax.swing.SpinnerNumberModel());
        albumRatingTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        albumRatingTxt.setFocusable(false);
        getContentPane().add(albumRatingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 165, 140, 35));

        rYearTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        rYearTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        rYearTxt.setFocusable(false);
        rYearTxt.setRequestFocusEnabled(false);
        getContentPane().add(rYearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 206, 140, 35));

        quantityTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        quantityTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 247, 140, 35));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 329, 118, 38));

        priceTxt.setBackground(new java.awt.Color(221, 221, 221));
        priceTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        priceTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(136, 330, 140, 38));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/pic1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 430));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        JFrame frame = new JFrame();
       
            album.setTracks(trackinfo.getTracks());
            if(trackinfo.getTracks().size()>0){
            try {
                if (controller.addAlbumsToDb(album)) {
                    JOptionPane.showMessageDialog(frame, "Album (  " + album.getTitle() + " ) Added ", "Message", JOptionPane.INFORMATION_MESSAGE);
                    this.dispose();
                }
                else
                    JOptionPane.showMessageDialog(frame, "Album cannot be Added !", "Alert", JOptionPane.ERROR_MESSAGE);      
            } catch (SQLException ex) {
                Logger.getLogger(AddAlbums.class.getName()).log(Level.SEVERE, null, ex);
            }
                }
                else {
                JOptionPane.showMessageDialog(frame, "Please add Songs!", "Alert", JOptionPane.ERROR_MESSAGE);
            }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame f = new JFrame();
        if (!title_txt.getText().isEmpty() && !priceTxt.getText().isEmpty()) {
            album.setTitle(title_txt.getText());
            try {
                album.setId(Integer.parseInt(id_txt.getText()));
                album.setReleaseYear(Integer.parseInt(getReleaseYear()));
                album.setQuantity(Integer.parseInt(quantityTxt.getValue().toString()));
                album.setGenre(genreTxt.getSelectedItem().toString());
                album.setRating(Integer.parseInt(albumRatingTxt.getValue().toString()));
                album.setPrice(Double.parseDouble(priceTxt.getText()));
                
                trackinfo.setVisible(true);
            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(f, ex.getMessage(),"Warning",JOptionPane.WARNING_MESSAGE);
            }
        } else {
                JOptionPane.showMessageDialog(f,"One or more fields are empty  !!" ,"Warning",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed

    }//GEN-LAST:event_formKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddAlbums.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddAlbums().setVisible(true);
            }
        });

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSpinner albumRatingTxt;
    private javax.swing.JComboBox<String> genreTxt;
    private javax.swing.JTextField id_txt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JSpinner quantityTxt;
    private javax.swing.JSpinner rYearTxt;
    private javax.swing.JTextField title_txt;
    // End of variables declaration//GEN-END:variables
}
