/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstoremanagement;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author SAM
 */
public class FindAlbum extends javax.swing.JFrame {

//    private Album album;
    private Controller controller;
//    private Track track;

    /**
     * Creates new form ShowQuantity
     */
    public FindAlbum() {
        initComponents();
//        album = new Album();
//        track = new Track();
        controller = new Controller();
        trackList.setBackground(new Color(221, 221, 221));
        trackList.setForeground(Color.BLACK);
        trackList.setColumns(5);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        findIdTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton9 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ratingTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ryearTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        quantityTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        genreTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        trackList = new javax.swing.JTextArea();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find Album");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        findIdTxt.setBackground(new java.awt.Color(221, 221, 221));
        findIdTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        findIdTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(findIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(384, 0, 140, 32));

        jLabel1.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel1.setText("Album ID");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 3, -1, -1));

        jButton9.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/find.png"))); // NOI18N
        jButton9.setText("Search Album");
        jButton9.setBorderPainted(false);
        jButton9.setContentAreaFilled(false);
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusPainted(false);
        jButton9.setFocusable(false);
        jButton9.setRequestFocusEnabled(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(349, 41, 181, -1));

        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Album ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 64, 122, 37));

        idTxt.setEditable(false);
        idTxt.setBackground(new java.awt.Color(221, 221, 221));
        idTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        idTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        idTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTxtActionPerformed(evt);
            }
        });
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 64, 140, 37));

        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 112, 122, 37));

        titleTxt.setEditable(false);
        titleTxt.setBackground(new java.awt.Color(221, 221, 221));
        titleTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        titleTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 112, 140, 37));

        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Rating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 155, 122, 37));

        ratingTxt.setEditable(false);
        ratingTxt.setBackground(new java.awt.Color(221, 221, 221));
        ratingTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        ratingTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(ratingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 155, 140, 37));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Release Year");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 198, 122, 37));

        ryearTxt.setEditable(false);
        ryearTxt.setBackground(new java.awt.Color(221, 221, 221));
        ryearTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        ryearTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(ryearTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 198, 140, 37));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Quantity");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 241, 122, 37));

        quantityTxt.setEditable(false);
        quantityTxt.setBackground(new java.awt.Color(221, 221, 221));
        quantityTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        quantityTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 241, 140, 37));

        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Genre");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 284, 122, 37));

        genreTxt.setEditable(false);
        genreTxt.setBackground(new java.awt.Color(221, 221, 221));
        genreTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        genreTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(genreTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 284, 140, 37));

        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Price");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 327, 122, 37));

        priceTxt.setEditable(false);
        priceTxt.setBackground(new java.awt.Color(221, 221, 221));
        priceTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        priceTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 327, 140, 37));

        trackList.setEditable(false);
        trackList.setBackground(new java.awt.Color(221, 221, 221));
        trackList.setColumns(20);
        trackList.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        trackList.setRows(5);
        trackList.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        trackList.setDisabledTextColor(new java.awt.Color(0, 0, 0));
        trackList.setEnabled(false);
        trackList.setSelectionColor(new java.awt.Color(0, 0, 0));
        jScrollPane2.setViewportView(trackList);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 112, 227, 292));

        jLabel9.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel9.setText("Find Album");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(101, 0, 200, 52));

        jLabel10.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel10.setText("Track List");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(307, 83, -1, -1));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/back.png"))); // NOI18N
        jButton1.setText("Back");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 376, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/al.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        jLabel11.setPreferredSize(new java.awt.Dimension(537, 426));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1200, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idTxtActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        int count = 1;
        int id ;
        if (!findIdTxt.getText().isEmpty()) {
            try {
                id = Integer.parseInt(findIdTxt.getText());
                Album a = controller.findAlbum(id);
                if (a != null) {
                    idTxt.setText(String.valueOf(a.getId()));
                    titleTxt.setText(a.getTitle());
                    ratingTxt.setText(String.valueOf(a.getRating()));
                    ryearTxt.setText(String.valueOf(a.getReleaseYear()));
                    quantityTxt.setText(String.valueOf(a.getQuantity()));
                    genreTxt.setText(a.getGenre());
                    priceTxt.setText(Double.toString(a.getPrice()));
                    for (Track t : a.getTracks()) {
                        trackList.setRows(a.getTracks().size());
                        trackList.append(count + "- " + t.getTitle() + "\n");
                        count++;
                        findIdTxt.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, " Album not found !!", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, " Please Type Album ID !!");
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindAlbum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindAlbum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField findIdTxt;
    private javax.swing.JTextField genreTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JTextField quantityTxt;
    private javax.swing.JTextField ratingTxt;
    private javax.swing.JTextField ryearTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JTextArea trackList;
    // End of variables declaration//GEN-END:variables
}
