/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstoremanagement;

import java.awt.Font;
import java.util.ArrayList;
import java.util.Vector;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumnModel;
import javax.swing.table.TableModel;

/**
 *
 * @author SAM
 */
public class FindCustomer extends javax.swing.JFrame {

    Controller controller = new Controller();
    /**
     * Creates new form FindCustomer
     */
    public FindCustomer() {
        initComponents();
        setTableLayout();
        setColumnWidths(jTable1,40, 150,70,70,150);


    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cIdTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        cNameTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        cAddressTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        findIdTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Find Customer");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(221, 221, 221));
        jTable1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        jTable1.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Album Title", "Quantity", "Price", "Date"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setEnabled(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 169, 413, 143));

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Find Customer");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(52, 0, 200, 52));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Customer ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 83, 122, 37));

        cIdTxt.setEditable(false);
        cIdTxt.setBackground(new java.awt.Color(221, 221, 221));
        cIdTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        cIdTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(cIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 83, 140, 37));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Full Name");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 126, 122, 37));

        cNameTxt.setEditable(false);
        cNameTxt.setBackground(new java.awt.Color(221, 221, 221));
        cNameTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        cNameTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(cNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 126, 140, 37));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Address");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 169, 122, 37));

        cAddressTxt.setEditable(false);
        cAddressTxt.setBackground(new java.awt.Color(221, 221, 221));
        cAddressTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        cAddressTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        getContentPane().add(cAddressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 169, 200, 143));

        jLabel5.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel5.setText("Sell Details");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(352, 134, -1, -1));

        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Find Customer");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(394, 3, -1, -1));

        findIdTxt.setBackground(new java.awt.Color(221, 221, 221));
        findIdTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        findIdTxt.setBorder(new javax.swing.border.LineBorder(java.awt.Color.gray, 1, true));
        findIdTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findIdTxtActionPerformed(evt);
            }
        });
        getContentPane().add(findIdTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 0, 140, 32));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/find.png"))); // NOI18N
        jButton1.setText("Find Customer");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(494, 38, -1, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 324, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/al.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 770, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void findIdTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findIdTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_findIdTxtActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int id ;
        if (!findIdTxt.getText().isEmpty()) {
            try {
                id = Integer.parseInt(findIdTxt.getText());
                Customer c = controller.findCustomer(id);
                if (c != null) {
                    cIdTxt.setText(String.valueOf(c.getId()));
                    cNameTxt.setText(c.getName());
                    cAddressTxt.setText(String.valueOf(c.getAddress()));
                    for (int i = 0; i < c.getAlbumTitles().size(); i++) {
            jTable1.setValueAt(c.getAlbumID().get(i), i, 0);
            jTable1.setValueAt(c.getAlbumTitles().get(i), i, 1);
            jTable1.setValueAt(c.getQuantities().get(i), i, 2);
            jTable1.setValueAt(c.getPrices().get(i), i, 3);
            jTable1.setValueAt(c.getDates().get(i), i, 4);

                }
                }
                else {
                    JOptionPane.showMessageDialog(null, " Customer not found !!", "Alert", JOptionPane.ERROR_MESSAGE);
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, " Please Type Customer ID !!");
        }
    }//GEN-LAST:event_jButton1ActionPerformed
private void setTableLayout() {
        jTable1.getTableHeader().setBackground(new java.awt.Color(221, 221, 221));
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(JLabel.CENTER);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        Font font = new Font("Sanserif", Font.BOLD, 15);
        jTable1.getTableHeader().setFont(font);
        jTable1.setRowHeight(29);
        

    }

    public static void setColumnWidths(JTable table, int... widths) {
    TableColumnModel columnModel = table.getColumnModel();
    for (int i = 0; i < widths.length; i++) {
        if (i < columnModel.getColumnCount()) {
            columnModel.getColumn(i).setMaxWidth(widths[i]);
        }
        else break;
    }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FindCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FindCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FindCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FindCustomer.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FindCustomer().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField cAddressTxt;
    private javax.swing.JTextField cIdTxt;
    private javax.swing.JTextField cNameTxt;
    private javax.swing.JTextField findIdTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
