package musicstoremanagement;

import java.awt.Color;
import java.awt.event.KeyEvent;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

public class RecordSales extends javax.swing.JFrame {

    private Controller controller;
    private double price;

    public RecordSales() {
        initComponents();
        setDate();
        controller = new Controller();
        jButton1.setEnabled(false);
        quantityTxt.setEnabled(false);
        changeSpinnerBg(dateTxt);
        changeSpinnerBg(quantityTxt);
    }

    private void setDate() {
        Calendar calender = Calendar.getInstance();
        SpinnerDateModel model = new SpinnerDateModel();
        model.setValue(calender.getTime());
        dateTxt.setModel(model);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(dateTxt, "dd/MM/yyyy HH:mm");
        dateTxt.setEditor(editor);
        dateTxt.setEnabled(false);

    }

    private void changeSpinnerBg(JSpinner spinner) {
        JTextField tf = ((JSpinner.DefaultEditor) spinner.getEditor()).getTextField();
        tf.setBackground(new Color(221, 221, 221));
        tf.setHorizontalAlignment(JTextField.CENTER);
        tf.setDisabledTextColor(Color.BLACK);
//         quantityTxt.se/tBackground(new Color(221, 221, 221));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        idTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        ratingTxt = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customeridTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        customerNameTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        dateTxt = new javax.swing.JSpinner();
        quantityTxt = new javax.swing.JSpinner();
        jLabel9 = new javax.swing.JLabel();
        priceTxt = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        addressTxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Record Sales");
        setPreferredSize(new java.awt.Dimension(325, 550));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Sell Record");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(74, 0, -1, 60));

        jLabel2.setBackground(new java.awt.Color(221, 221, 221));
        jLabel2.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel2.setText("Album ID");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 65, 122, 37));

        idTxt.setBackground(new java.awt.Color(221, 221, 221));
        idTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        idTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        idTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                idTxtKeyReleased(evt);
            }
        });
        getContentPane().add(idTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 65, 140, 37));

        jLabel3.setBackground(new java.awt.Color(221, 221, 221));
        jLabel3.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel3.setText("Title");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 108, 122, 37));

        titleTxt.setEditable(false);
        titleTxt.setBackground(new java.awt.Color(221, 221, 221));
        titleTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        titleTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 107, 140, 37));

        jLabel4.setBackground(new java.awt.Color(221, 221, 221));
        jLabel4.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel4.setText("Rating");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 151, 122, 37));

        ratingTxt.setEditable(false);
        ratingTxt.setBackground(new java.awt.Color(221, 221, 221));
        ratingTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        ratingTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(ratingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 149, 140, 37));

        jLabel5.setBackground(new java.awt.Color(221, 221, 221));
        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Quantity");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 194, 122, 37));

        jLabel6.setBackground(new java.awt.Color(221, 221, 221));
        jLabel6.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel6.setText("Customer ID");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 236, 122, 37));

        customeridTxt.setBackground(new java.awt.Color(221, 221, 221));
        customeridTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        customeridTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        customeridTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customeridTxtActionPerformed(evt);
            }
        });
        customeridTxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                customeridTxtKeyReleased(evt);
            }
        });
        getContentPane().add(customeridTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 233, 140, 37));

        jLabel7.setBackground(new java.awt.Color(221, 221, 221));
        jLabel7.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel7.setText("Full Name");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 279, 122, 37));

        customerNameTxt.setBackground(new java.awt.Color(221, 221, 221));
        customerNameTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        customerNameTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(customerNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 275, 140, 37));

        jLabel8.setBackground(new java.awt.Color(221, 221, 221));
        jLabel8.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel8.setText("Date");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 364, 122, 37));

        dateTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 12)); // NOI18N
        dateTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        dateTxt.setFocusable(false);
        dateTxt.setRequestFocusEnabled(false);
        dateTxt.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(dateTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 357, 140, 37));

        quantityTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        quantityTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        quantityTxt.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                quantityTxtStateChanged(evt);
            }
        });
        getContentPane().add(quantityTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 191, 140, 37));

        jLabel9.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel9.setText("Price");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 408, 122, 37));

        priceTxt.setEditable(false);
        priceTxt.setBackground(new java.awt.Color(221, 221, 221));
        priceTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        priceTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(priceTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 402, 140, 37));

        jLabel10.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel10.setText("Address");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 321, 122, 37));

        addressTxt.setBackground(new java.awt.Color(221, 221, 221));
        addressTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        addressTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(addressTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 316, 140, 37));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/save.png"))); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(31, 457, -1, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(146, 457, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/pic1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 349, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel11))
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void idTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_idTxtKeyReleased
      if(!idTxt.getText().isEmpty()&&evt.getKeyCode()!=KeyEvent.VK_BACK_SPACE
              &&evt.getKeyCode()!=KeyEvent.VK_ENTER){
        Album a;
        int id ;
        try {
            id = Integer.parseInt(idTxt.getText());
            a=controller.findAlbum(id);
            if (a!=null) {
                titleTxt.setText(a.getTitle());
                ratingTxt.setText(String.valueOf(a.getRating()));
                price = a.getPrice();
                priceTxt.setText(String.valueOf(price));
                quantityTxt.setEnabled(true);
                SpinnerModel value =  
                new SpinnerNumberModel(1,  1,  a.getQuantity(),  1); 
                quantityTxt.setModel(value);
                changeSpinnerBg(quantityTxt);
                jButton1.setEnabled(true);
            } else {
                titleTxt.setText("Album not found");
                ratingTxt.setText("Album not found");
                priceTxt.setText("");
                quantityTxt.setEnabled(false);
                quantityTxt.setValue(0);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }}
    }//GEN-LAST:event_idTxtKeyReleased

    private void quantityTxtStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_quantityTxtStateChanged
        try {
            priceTxt.setText(String.valueOf(price * Double.parseDouble(quantityTxt.getValue().toString())));
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_quantityTxtStateChanged

    private void customeridTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customeridTxtActionPerformed
        
    }//GEN-LAST:event_customeridTxtActionPerformed

    private void customeridTxtKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_customeridTxtKeyReleased
        if(!customeridTxt.getText().isEmpty()&&evt.getKeyCode()!=KeyEvent.VK_BACK_SPACE
              &&evt.getKeyCode()!=KeyEvent.VK_ENTER){
        int id=0;
        Customer c ;
        try {
            id = Integer.parseInt(customeridTxt.getText());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }
      c = controller.findCustomer(id);
        if (c != null) {
            customerNameTxt.setText(c.getName());
            addressTxt.setText(c.getAddress());
        } else{
            customerNameTxt.setText("");
            addressTxt.setText("");
        }}
    }//GEN-LAST:event_customeridTxtKeyReleased

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int albumID;
        int quantity;
        int cID;
        double albumsPrice;
        String cName;
        String address;
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
        try {
            if (!customerNameTxt.getText().isEmpty() && !customeridTxt.getText().isEmpty()
                    && !addressTxt.getText().isEmpty() && !idTxt.getText().isEmpty()
                    && !"0".equals(quantityTxt.getValue().toString())) {
                albumID = Integer.parseInt(idTxt.getText());
                quantity = Integer.parseInt(quantityTxt.getValue().toString());
                cID = Integer.parseInt(customeridTxt.getText());
                albumsPrice = Double.parseDouble(priceTxt.getText());
                cName = customerNameTxt.getText();
                address=addressTxt.getText();
                int response = JOptionPane.showConfirmDialog(null, "Do you want to continue?", "Confirm",
                        JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
                if (response == JOptionPane.YES_OPTION) {
                   if( controller.sellAlbum(albumID, quantity, cID, cName,address, albumsPrice, dateFormat.format(dateTxt.getValue()))){
                    JOptionPane.showMessageDialog(null, "Successfully Added !");    
                    this.dispose();
                   }
                   else{
                                           JOptionPane.showMessageDialog(null, "Some Error !","Error",JOptionPane.ERROR_MESSAGE);    
                   }
                } else {
                    idTxt.setText("");
                    addressTxt.setText("");
                    titleTxt.setText("");
                    ratingTxt.setText("");
                    quantityTxt.setValue(0);
                    customerNameTxt.setText("");
                    customeridTxt.setText("");
                    jButton1.setEnabled(false);
                }
            } else {
                JOptionPane.showMessageDialog(null, "One or more fields are empty  !!", "Warning", JOptionPane.WARNING_MESSAGE);
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RecordSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RecordSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RecordSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RecordSales.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RecordSales().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressTxt;
    private javax.swing.JTextField customerNameTxt;
    private javax.swing.JTextField customeridTxt;
    private javax.swing.JSpinner dateTxt;
    private javax.swing.JTextField idTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField priceTxt;
    private javax.swing.JSpinner quantityTxt;
    private javax.swing.JTextField ratingTxt;
    private javax.swing.JTextField titleTxt;
    // End of variables declaration//GEN-END:variables
}
