/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package musicstoremanagement;

import java.awt.Color;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.JTextField;
import javax.swing.SpinnerDateModel;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author SAM
 */
public class TrackInfo extends javax.swing.JFrame {

    private Album album;
    private Track track;
    private Singer singer;

    public TrackInfo() {
        initComponents();
        setLanguages();
        setTimeDuration();
        album = new Album();

        SpinnerModel model = new SpinnerNumberModel(5, 1, 5, 1);
        trackRatingTxt.setModel(model);
        model = new SpinnerNumberModel(5, 1, 5, 1);
        sRatingTxt.setModel(model);
        spinnerBgChanger(trackDurationTxt);
        spinnerBgChanger(trackRatingTxt);
        spinnerBgChanger(sRatingTxt);
    }

    private void spinnerBgChanger(JSpinner spinner) {
        JTextField tf = ((JSpinner.DefaultEditor) spinner.getEditor()).getTextField();
        tf.setBackground(new Color(221, 221, 221));
        tf.setHorizontalAlignment(JTextField.CENTER);
        languageTxt.setBackground(new Color(221, 221, 221));

    }

    private void setLanguages() {
        album = new Album();
        languageTxt.removeAllItems();
        for (String language : new Track().getLanguages()) {
            languageTxt.addItem(language);
        }
    }

    private void setTimeDuration() {
        Calendar calendar = Calendar.getInstance();
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        SpinnerDateModel model = new SpinnerDateModel();
        model.setValue(calendar.getTime());
        trackDurationTxt.setModel(model);
        JSpinner.DateEditor editor = new JSpinner.DateEditor(trackDurationTxt, "mm:ss");
        trackDurationTxt.setEditor(editor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        titleTxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        languageTxt = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        trackDurationTxt = new javax.swing.JSpinner();
        jLabel5 = new javax.swing.JLabel();
        trackRatingTxt = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        sNameTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        sRatingTxt = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        infoTxt = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Tracks");
        setBounds(new java.awt.Rectangle(80, 80, 0, 0));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Sans", 0, 24)); // NOI18N
        jLabel1.setText("Add Tracks");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 0, 180, 60));

        jLabel2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel2.setText("Title");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 66, 122, 38));

        titleTxt.setBackground(new java.awt.Color(221, 221, 221));
        titleTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        titleTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(titleTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 66, 140, 38));

        jLabel3.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel3.setText("Language");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 110, 122, 38));

        languageTxt.setBackground(new java.awt.Color(221, 221, 221));
        languageTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        languageTxt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        languageTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(languageTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 110, 141, 38));

        jLabel4.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel4.setText("Duration");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 154, 122, 38));

        trackDurationTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        trackDurationTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        trackDurationTxt.setFocusable(false);
        trackDurationTxt.setRequestFocusEnabled(false);
        trackDurationTxt.setVerifyInputWhenFocusTarget(false);
        getContentPane().add(trackDurationTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 154, 141, 38));

        jLabel5.setFont(new java.awt.Font("SansSerif", 0, 18)); // NOI18N
        jLabel5.setText("Rating");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 198, 122, 39));

        trackRatingTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        trackRatingTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(trackRatingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 198, 141, 39));

        jLabel6.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel6.setText("Singer Name");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 243, 122, 38));

        sNameTxt.setBackground(new java.awt.Color(221, 221, 221));
        sNameTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        sNameTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        sNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(sNameTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 243, 141, 38));

        jLabel7.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jLabel7.setText("Singer Rating");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 287, 122, 38));

        sRatingTxt.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 15)); // NOI18N
        sRatingTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(188, 188, 188), 1, true));
        getContentPane().add(sRatingTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 287, 141, 38));

        jButton1.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/add.png"))); // NOI18N
        jButton1.setText("Add Track");
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 343, -1, -1));

        jButton2.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/back.png"))); // NOI18N
        jButton2.setText("Back");
        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(151, 343, 124, -1));

        infoTxt.setEditable(false);
        infoTxt.setBackground(new java.awt.Color(221, 221, 221));
        infoTxt.setFont(new java.awt.Font("sansserif", 0, 18)); // NOI18N
        infoTxt.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(188, 188, 188)));
        getContentPane().add(infoTxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 391, 277, 44));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/musicstoremanagement/images/pic1.jpg"))); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 440));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void sNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_sNameTxtActionPerformed
    private String getTrackDuration() {
        Object value = trackDurationTxt.getValue();
        if (value instanceof Date) {
            Date date = (Date) value;
            SimpleDateFormat format = new SimpleDateFormat("mm:ss");
            String time = format.format(date);
            return time;
        }
        return "00:00";
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        JFrame frame = new JFrame();
        if (!titleTxt.getText().isEmpty() && !sNameTxt.getText().isEmpty()) {
            try {
                singer = new Singer(sNameTxt.getText(), Integer.parseInt(sRatingTxt.getValue().toString()));
                track = new Track(titleTxt.getText(), getTrackDuration(), singer, Integer.parseInt(trackRatingTxt.getValue().toString()), languageTxt.getSelectedItem().toString());
                if (album.addTrack(track)) {
                    titleTxt.setText("");
                    sNameTxt.setText("");
                    infoTxt.setText(album.getTracks().size() + " Track Added !!");
                } else {
                    infoTxt.setText(" Track Already Added !!");
                }
            } catch (NumberFormatException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(), "Warning", JOptionPane.WARNING_MESSAGE);

            }

        } else {
            JOptionPane.showMessageDialog(null, "One or more fields are empty  !!", "Warning", JOptionPane.WARNING_MESSAGE);

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed
    public ArrayList getTracks() {
        return album.getTracks();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackInfo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField infoTxt;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> languageTxt;
    private javax.swing.JTextField sNameTxt;
    private javax.swing.JSpinner sRatingTxt;
    private javax.swing.JTextField titleTxt;
    private javax.swing.JSpinner trackDurationTxt;
    private javax.swing.JSpinner trackRatingTxt;
    // End of variables declaration//GEN-END:variables
}
